#
# unlock-all.yml
# Unlock all locked issues
#

name: "Unlock all locked"

on:
  schedule:
    - cron: '* 10/40 * * *'

jobs:
  lock:
    runs-on: ubuntu-latest
    steps:
    - uses: OSDKDev/unlock-issues@v1.1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
